from django.shortcuts import render
from .models import skill,Contact
from django.contrib import messages
from django.core.mail import send_mail,send_mass_mail
from django.conf import settings


# Create your views here.
def home(request):
    skills = skill.objects.filter(status=1)
    return render(request,'index.html',{'skills':skills})


def contact(request):
    if request.method== 'POST':
        name=request.POST['name']
        email=request.POST['email']
        message=request.POST['message']
        

        # form validation
        if len(name)<3:
            messages.error(request, 'please fill your name correctly ')
        
        if len(message)<5:
            messages.error(request, 'please write your message in detail ')
       
        else:
            contact = Contact(name = name, email = email, message = message,)
            contact.save()
            messages.success(request, 'Thank you! will contact you soon ')
            message1 = f'hi {name}!\n\n Thanks for contacting Jairaj this is autogenerated mail.\nJairaj will contact you soon.\n\n Thank you.'
            message2 = (
                     'contacting jairaj',
                    message1,
                    settings.EMAIL_HOST_USER,
                    [email,],
                       )

            message3 = ('someone contacted you',f'hey Jairaj\n one user just tried to contact you \n NAME: {name}\n EMAIL: {email}\n MESSAGE:{message}',settings.EMAIL_HOST_USER,['jairajkumar3105@gmail.com'])
            send_mass_mail((message2, message3), fail_silently=False)
    
    return render(request, 'contact.html')